pmndrs/docs

- components/Nav.tsx
- components/Toc.tsx
- docs/react-three-fiber/advanced/instancing.mdx
- pages/[...slug].tsx
- utils/mdxUtils.ts
This pull request addresses [the issues I found and shared on Discord](https://discord.com/channels/740090768164651008/810837017482362901/814986922241556480) with accessing and routing docs across machines.
I've cleaned up all the regex that touches paths to be agnostic to whichever OS you are on (see [`path.sep`](https://nodejs.org/api/path.html#path_path_sep)) and cleaned up that logic in the [`getDocsPaths`](https://github.com/CodyJasonBennett/website/blob/docs-path-fix/utils/mdxUtils.ts#L11-L21) method.
> Improve regex and fix doc paths to be OS agnostic.

- pages/[...slug].tsx
- remark/withTableofContents.ts
- utils/mdxUtils.ts
Wraps up some housekeeping for the fix in #13.
Table of Contents generation was moved to the remark plugins folder, and the mdxUtils work a bit more explicitly. We can move any config or imports related to prism there as well.
> Docs: cleanup MDX, remark.

- components/Sandbox.tsx
This fixes the following warning: `Anonymous arrow functions cause Fast Refresh to not preserve local component state.`
> Fix missing component name for Sandbox

- css/main.css
Currently when clicking on the anchors in TOC, i.e. `On this page`, the heading of the target is blocked by the search bar. This PR improves the UI by adding `scroll-margin-top` to anchor targets inside `.content-container`
> Add scroll-margin-top to anchor targets in content

- license
> Continued from #63
I'm mirroring the license from react-spring ([the fixed ones](https://github.com/pmndrs/react-spring/pull/1480/files#diff-de9e7884e3b0ae3ca60f078e425c1a845fbd76f92adf3ffe8d95f3db7e498b08)), but there may be some things to review, like the use of present versus a range and who to attribute.
> docs: update license

- components/Layout.tsx
When you click `Edit this page on Github` in any docs, It redirects you to different .mdx file in the repository.
> fix: Fix url for "Edit this page on Github"

- docs/jotai/api/devtools.mdx
This adds documentation for two new hooks in Jotai, which is meant for debugging and creation of devtools.
> docs(jotai): Add documentation for useAtomsSnapshot and useGotoAtomsSnapshot

- docs/jotai/basics/concepts.mdx
broken link to comparison page
> Fix: broken link to comparison page

- docs/jotai/advanced-recipes/atom-creators.mdx
This doc adds a page in `jotai` section `advanced-recipes` based on the outcome of the discussion of this PR https://github.com/pmndrs/jotai/pull/483
> docs(jotai): add atom-creators/atomWithToggle

- docs/drei/abstractions/cubic-bezier-line.mdx
- docs/drei/abstractions/line.mdx
- docs/drei/abstractions/positional-audio.mdx
- docs/drei/abstractions/quadratic-line.mdx
- docs/drei/cameras/cube-camera.mdx
- docs/drei/controls/introduction.mdx
- docs/drei/controls/map-controls.mdx
- docs/drei/performance/detailed.mdx
- docs/drei/shaders/shader-material.mdx
- docs/react-three-fiber/API/canvas.mdx
- docs/react-three-fiber/API/events.mdx
- docs/react-three-fiber/API/hooks.mdx
- docs/react-three-fiber/API/objects.mdx
- docs/react-three-fiber/advanced/how-it-works.mdx
- docs/react-three-fiber/advanced/pitfalls.mdx
- docs/react-three-fiber/getting-started/basic-animations.mdx
- docs/react-three-fiber/getting-started/events-and-interaction.mdx
- docs/react-three-fiber/getting-started/installation.mdx
- docs/react-three-fiber/getting-started/loading-models.mdx
- docs/react-three-fiber/getting-started/loading-textures.mdx
- docs/react-three-fiber/getting-started/using-with-react-spring.mdx
- docs/react-three-fiber/getting-started/your-first-scene.mdx
Hi all, thanks for the great library and the new docs. I particularly like the conversational style and ample demos.
I made a bunch of formatting fixes, fixed typos and improved a few sentences. Also I noticed that three.js was written a variety of ways (ThreeJS, Threejs, Three.js, threejs, three.js, Three.js), not a very big deal but it's nice if things are consistent so I changed all to 'three.js'. I went for this one because that's how it's written in the three.js docs.
Some goes for react-three/fiber which alternately written as 'Fiber', 'React Three Fiber', 'react-three-fiber', 'react three fiber'. Again, I think it's better if this is consistent throughout the docs. My vote goes to 'react-three/fiber' or React Three Fiber. I think 'Fiber' is too ambiguous and  'react-three-fiber' …
> Fix typos and formatting, consistent naming of three.js

- components/Layout.tsx
Menu Icon should be visible until 1024px screen width, otherwise there is no menu between 768 and 1023px screen width.
> Menu Icon visibility

- components/LibSwitcher.tsx
currently, for example, if you want to go from  `jotai` docs to `zustand`, it redirects you to `/jotai/zustand` .
this PR fixes that.
> Prefix data libraries item in Link with /

- docs/jotai/basics/primitives.mdx
`/jotai/async` -> `/jotai/basics/async`
> Fix the broken link

- css/main.css
- pages/_app.tsx
From: #102.
This pull request preloads global fonts and changes their display behavior to maintain visibility.
Related:
- https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload
> fix(docs): preload fonts to avoid initial flash

- docs/jotai/api/utils.mdx
`birth.time.hour` and `minute` had type `number`, not valid values.
> Fix `selectAtom` example

- remark/withTableofContents.ts
Continues #93.
Headings do not display nor link right in production when they only contain inline code.
An issue with the current implementation is that authors do not provide alternate text for some snippets. This means that we have to guess what to call each method/property. When listing different forms of arguments for some methods, subsequent will point to their parent (see [react-spring/classes/spring-value#start](https://website-git-fix-code-titles-pmndrs.vercel.app/react-spring/classes/spring-value#start)).
> fix(docs): parse snippets in headings, fix associated links

- next.config.js
Configures next to treat codesandbox thumbnails as external images.
> fix(docs): inform next about external images

- docs/a11y/access-user-preferences.mdx
I noticed that the link to pmndrs/react-three-fiber#43 had a typo in it. This removes the extra `h` from `hhttps`
> Fix link to multiple renderers

- docs/react-three-fiber/getting-started/loading-models.mdx
Currently this link points to `https://docs.pmnd.rs/react-three-fiber/getting-started/gltf.pmnd.rs`
> Correct link to https://gltf.pmnd.rs/

- docs/jotai/integrations/xstate.mdx
Replaces "privimite" with "primitive".
> Fix typo in Jotai's XState integration page

- docs/react-three-fiber/advanced/scaling-performance.mdx
> Fix typo from "supsense" to "suspense"

- docs/zustand/introduction.mdx
> Fixing missing zustand-bear logo on the zustand docs introduction page

- next.config.js
Fixes #139 by adding redirects for moved docs from https://github.com/pmndrs/website/commit/d5b3960cf189046f30dabcb75a559272dff1ce54 and https://github.com/pmndrs/website/commit/0f03414a787b9728becf7c2ad17b08118f2f3066.
> fix(docs): add redirects for altered routes

- docs/jotai/introduction.mdx
I was reading `jotai` docs and noticed that the `Jotai` SVG isn't loading. So I tried fixing it. Please close this PR if you don't like these types of PR.
> fix: svg logo title not showing

- docs/jotai/api/utils.mdx
- docs/jotai/guides/nextjs.mdx
- next-env.d.ts
Add docs for useHydrateAtoms. It's missing an example, I'll try to add an example to the Next.js using Jotai.
> Jotai: add useHydrateAtoms docs

- docs/react-three-fiber/advanced/scaling-performance.mdx
Just found a small typo in the example code
> Fixed a typo in the docs

- docs/react-spring/classes/spring-value.mdx
- docs/react-spring/components/spring.mdx
- docs/react-spring/components/trail.mdx
- docs/react-spring/components/transition.mdx
- docs/react-spring/getting-started.mdx
- docs/react-spring/hooks/use-spring.mdx
- docs/react-spring/hooks/use-springs.mdx
- docs/react-spring/hooks/use-trail.mdx
- docs/react-spring/hooks/use-transition.mdx
- next-env.d.ts
While reading the documentation for `react-spring` I noticed that a few of the internal links were broken. This PR tries to fix some of them (the ones I caught).
> fix(docs): react-spring broken links

- components/Layout.tsx
- components/Modal.tsx
- components/Search/index.tsx
- hooks/useLockBodyScroll.ts
Has the hook only apply to the client and gets rid of the scary react server warnings. Nothing in uppercase and no underscores, so we're probably fine.
> fix(useLockBodyScroll): keep effect in client

- docs/jotai/advanced-recipes/large-objects.mdx
Fix a small typo by replacing a single word.
> Fix small typo

- package.json
Bump up Next.js to latest release: v11
> chore: Bump up Next.js to latest v11.

- components/Toc.tsx
- components/mdx/index.tsx
- remark/withTableofContents.ts
Updates the ToC to only include unique links and generates labels to address the accessibility issues outlined in #119.
Test links (`react-spring/classes/spring-value#start`):
- [prod](https://docs.pmnd.rs/react-spring/classes/spring-value#start)
- [PR](https://website-git-fix-dedup-toc-pmndrs.vercel.app/react-spring/classes/spring-value#start)
> fix(docs): remove duplicate ToC links, generate labels

- components/mdx/Sandbox.tsx
- css/main.css
Fixes #187 by both rendering a skeleton for suspended sandboxes and waits to load them until they've entered view.
You can compare the layout shifts between [prod](https://docs.pmnd.rs/react-three-fiber/getting-started/examples#game-prototypes) and [this pr](https://website-git-fix-docs-sandbox-pmndrs.vercel.app/react-three-fiber/getting-started/examples#game-prototypes).
> docs(Sandbox): render loading skeletons, lazy load sections

- docs/drei/controls/introduction.mdx
According to https://github.com/pmndrs/react-three-fiber/blob/master/markdown/changelog.md#removal-of-useresource, it seems we should use `useState` instead of `useResource`.
> docs(drei): change useResource to useState

- docs/react-three-fiber/getting-started/installation.mdx
- docs/react-three-fiber/getting-started/introduction.mdx
Adds installation and usage instructions for react-native to R3F docs for the upcoming beta release.
> docs(fiber): add native installation instructions & example

- components/LibSwitcher.tsx
- components/Seo.tsx
- data/libraries.js
- pages/home.tsx
Removes hardcoded SEO for libraries and pulls from `data/libraries`. This was made to unify configuration in #204, but I'm backporting this to tidy things up.
> chore: cleanup SEO

- docs/react-three-fiber/API/canvas.mdx
Fixes #203 where hints are unformatted by adding newlines to have MDX explicitly format plaintext.
> docs(R3F): fix markdown transclusion in Canvas hints

- docs/react-three-fiber/tutorials/how-it-works.mdx
The import mentioned in https://docs.pmnd.rs/react-three-fiber/tutorials/how-it-works seems to be wrong. 
I believe `useCamera` was exported from `@react-three/fiber` initially but moved to `@react-three/drei` later on and this was not updated on the docs. Updated that in this PR.
> Fix wrong import in documentation

- components/mdx/index.tsx
- docs/react-three-fiber/API/events.mdx
- docs/react-three-fiber/advanced/scaling-performance.mdx
This is a non-issue for MDX v2 or mdx-bundler, but this ensures that we can use any compiler without duplication.
> chore(mdx): remove duplicate InlineCode & cleanup R3F transclusion

- utils/mdx.ts
Switches git protocols as per the depreciation in https://github.blog/2021-09-01-improving-git-protocol-security-github/.
> fix: use https for git

- docs/drei/staging/stage.mdx
- docs/drei/staging/use-matcap-texture.mdx
- docs/drei/staging/use-normal-texture.mdx
Fixes #228 by updating Drei's prototyping section to reference the new staging stories.
> docs(Drei): prototyping => staging

- docs/a11y/advanced/gotchas.mdx
- docs/react-postprocessing/effects/ssao.mdx
- docs/react-spring/changelog.mdx
- docs/react-spring/common/configs.mdx
Fixes some of the syntax errors that popped up during the parser upgrade (MDX 1 => MDX 2) in #232.
> chore: fix invalid MDX syntax

- components/Layout.tsx
- components/Search/SearchItem.tsx
- components/Search/SearchModal.tsx
- components/Search/index.tsx
- components/Toc.tsx
- hooks/useDocs.ts
- pages/[...slug].tsx
- tsconfig.json
- utils/docs.ts
- utils/rehype.ts
- utils/text.ts
Improves search relevance by including page headings and their descriptions in search results. Search results are also properly ranked by match % instead of the starting index (which would de-rank complete matches).
https://user-images.githubusercontent.com/23324155/185773909-9435f674-b90b-4568-98a7-25dfada75e3e.mp4
> feat: improve search relevance

- src/components/Search/SearchItem.tsx
- src/components/Search/SearchModal.tsx
- src/components/Search/index.tsx
- src/hooks/useDocs.ts
- src/utils/docs.ts
Shows page titles in search. Also excludes page descriptions from search results.
https://user-images.githubusercontent.com/23324155/185799047-f791583e-21a4-4c98-8959-00b6d90403de.mp4
> refactor: label results' pages in search

- src/components/Post.tsx
- src/utils/docs.ts
Referring to this conversation: https://github.com/pmndrs/zustand/pull/1257#discussion_r962101354
The site needs to support links that contain the `.md` extention so the docs work within Github, but also on the documentation site. 
Example: 
TypeScript link on this page is broken due to the inclusion of the .md extension:
https://docs.pmnd.rs/zustand/guides/flux-inspired-practice
It's worth noting that over in r3f land, internal docs links are treated as full paths such as events on this page: https://docs.pmnd.rs/react-three-fiber/getting-started/installation
This PR won't impact those. 
**Alternatives**
Option 1: Ideally I would've preferred to use something like `new URL(relativeHref, location)` to parse the parts of the href but I'm not sure how to thread through the location in next …
> feat: remove .md extension when parsing anchor components

- src/components/Post.tsx
- src/utils/docs.ts
This address this issue in Zustand: https://github.com/pmndrs/zustand/issues/1313
At the moment, titles with a code tag, like "`create` without curried workaround" result in `undefined` as the id.
This PR flattens those ids into a single string
> fix: flatten headings that contain non-string elements

- public/robots.txt
- src/components/Layout.tsx
- src/components/Post.tsx
- src/components/Toc.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
Makes correct use of headings and SEO configuration. WIP image implementation that will have to be followed up with a rehype plugin to assert its use whenever HTML is explicitly defined in markdown (related: https://github.com/pmndrs/react-three-fiber/commit/e211dbf09461c153d768cad53d439a5fbdcc0b5e, https://github.com/pmndrs/react-three-fiber/commit/66776edb25da84409c25cd01b8001eb414f4385f, https://github.com/pmndrs/react-three-fiber/commit/0a8f3c26d67c61d58d5397de671c38ce2cfcac3a).
> refactor: basic audit for SEO

- src/components/Search/SearchModal.tsx
- src/hooks/useLockBodyScroll.ts
Prevents layout shifts by applying a computed page offset whenever scrollbar visibility is changed.
> fix(useLockBodyScroll): prevent CLS when hiding scrollbar

- docs/getting-started/authoring.mdx
- src/app/globals.css
> Add support for code highlighting and line numbers

- src/components/Search/SearchModalContainer.tsx
- src/utils/text.ts
Resolves regex errors in SearchModal caused by unescaped special characters in user input.
https://github.com/user-attachments/assets/c717a695-dc66-472d-886c-be8119dcdbb0
https://github.com/user-attachments/assets/490fb206-4694-4ade-80f4-06b3b2179aa3
> fix: Escape special characters in SearchModal to prevent regex errors

- src/components/mdx/Codesandbox/Codesandbox.tsx
The current ordering of props destructuring prevents applying custom screenshot_url to CSBs. This quick PR fixes that.
> User-passed props should overwrite those returned by fetchCSB

- src/app/[...slug]/layout.tsx
`<a>`'s [`rel=next`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel#next)/[`rel=prev`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel#prev) enable accessibility software to detect the relationship between pages. (Next.js passes props like this straight through from `<Link>`.)
> feat: Add `rel` attributes to next/prev links
