pmndrs/docs

- components/LibSwitcher.tsx
- docs/react-three-fiber/getting-started/basic-animations.mdx
- docs/react-three-fiber/getting-started/events-and-interaction.mdx
- docs/react-three-fiber/getting-started/testing.mdx
https://codesandbox.io/s/interaction-98ppy
Page: https://website-git-interactions-pmndrs.vercel.app/react-three-fiber/getting-started/events-and-interaction
> add Events and Interaction page

- components/Layout.tsx
- components/Search.tsx
- docs/react-three-fiber/advanced/how-it-works.mdx
- docs/react-three-fiber/getting-started/basic-animations.mdx
- docs/react-three-fiber/getting-started/introduction.mdx
- docs/react-three-fiber/getting-started/using-with-react-spring.mdx
- docs/react-three-fiber/getting-started/your-first-scene.mdx
- package.json
- pages/[...slug].tsx
- Adds starter sandbox that is the one in the repo
- remove all mentions of simple
- Makes the search work
- Creates Link component that makes all external links open in a new tab
-
> Small UI and text changes

- docs/react-three-fiber/advanced/pitfalls.mdx
- docs/react-three-fiber/getting-started/basic-animations.mdx
- docs/react-three-fiber/getting-started/loading-textures.mdx
- docs/react-three-fiber/getting-started/state-management.mdx
- docs/react-three-fiber/getting-started/testing.mdx
- pages/[...slug].tsx
Adds testing and pitfalls sections
> add testing and Performance pitfalls

- components/Layout.tsx
- css/main.css
- docs/react-three-fiber/API/addtional-exports.mdx
- docs/react-three-fiber/API/automatic-disposal.mdx
- docs/react-three-fiber/API/canvas.mdx
- docs/react-three-fiber/API/events.mdx
- docs/react-three-fiber/API/gotchas.mdx
- docs/react-three-fiber/API/objects.mdx
- docs/react-three-fiber/API/render-function.mdx
- docs/react-three-fiber/advanced/how-it-works.mdx
- docs/react-three-fiber/advanced/instancing.mdx
- docs/react-three-fiber/advanced/pitfalls.mdx
- docs/react-three-fiber/getting-started/events-and-interaction.mdx
- docs/react-three-fiber/getting-started/loading-models.mdx
- docs/react-three-fiber/getting-started/loading-textures.mdx
- docs/react-three-fiber/getting-started/testing.mdx
- docs/react-three-fiber/getting-started/using-with-react-spring.mdx
- docs/react-three-fiber/hooks/useFrame.mdx
- docs/react-three-fiber/hooks/useGraph.mdx
- docs/react-three-fiber/hooks/useLoader.mdx
- docs/react-three-fiber/hooks/useThree.mdx
- next.config.js
- pages/[...slug].tsx
- pages/index.tsx
- pages/react-three-fiber/index.tsx
- utils/mdxUtils.ts
* Adds API pages, most where copy and paste
* Adds mobile menu
* Makes redirects non permenent
> Adds API pages

- components/Codesandbox.tsx
- components/Layout.tsx
- components/MDXComponents.tsx
- css/main.css
- docs/react-three-fiber/examples.mdx
- docs/react-three-fiber/getting-started/basic-animations.mdx
- docs/react-three-fiber/getting-started/events-and-interaction.mdx
- docs/react-three-fiber/getting-started/loading-models.mdx
- docs/react-three-fiber/getting-started/loading-textures.mdx
- docs/react-three-fiber/getting-started/testing.mdx
- docs/react-three-fiber/getting-started/using-with-react-spring.mdx
- docs/react-three-fiber/getting-started/your-first-scene.mdx
- pages/[...slug].tsx
- Adds page of examples
- Removes TOC if no items
- Adds edit on github link
- Creates codesandbox component now with light theme
> Add example pages

- components/MDXComponents.tsx
- components/Sandbox.tsx
- docs/react-three-fiber/examples.mdx
- docs/react-three-fiber/getting-started/installation.mdx
- docs/react-three-fiber/getting-started/introduction.mdx
- package.json
- pages/api/get-sandbox.ts
Creates sandbox component to get a sandbox info and show it for examples
> Sandbox component

- components/MDXComponents.tsx
- docs/react-three-fiber/API/automatic-disposal.mdx
- docs/react-three-fiber/API/canvas.mdx
- docs/react-three-fiber/API/events.mdx
- docs/react-three-fiber/API/objects.mdx
- docs/react-three-fiber/API/render-function.mdx
- docs/react-three-fiber/advanced/pitfalls.mdx
- docs/react-three-fiber/getting-started/basic-animations.mdx
- docs/react-three-fiber/getting-started/events-and-interaction.mdx
- docs/react-three-fiber/getting-started/installation.mdx
- docs/react-three-fiber/getting-started/introduction.mdx
- docs/react-three-fiber/getting-started/loading-models.mdx
- docs/react-three-fiber/getting-started/testing.mdx
- docs/react-three-fiber/getting-started/using-with-react-spring.mdx
- docs/react-three-fiber/getting-started/your-first-scene.mdx
Mostly a lot of small fixes for consistency and style of the writing
> Consistency and style fixes

- docs/react-three-fiber/getting-started/installation.mdx
This includes an updated example of R3F using no build tools per @drcmda's request
https://codepen.io/mattrossman/pen/mdRGJBy
The codepen link should be replaced with something from a stable Poimandres account.
> Add example with skypack and htm

- components/Layout.tsx
- components/LibSwitcher.tsx
- components/Modal.tsx
- package.json
- pages/drei/index.tsx
- pages/react-spring/index.tsx
- pages/react-three-fiber/index.tsx
- store/menu.ts
- store/switcher.ts
- utils/useLockBodyScroll.ts
Uses the work here https://github.com/pmndrs/website/pull/12 from @emmelleppi and cleans up all the conflicts and fixes the names and links
> Lib Switcher

- components/Layout.tsx
- components/Search.tsx
- hooks/useKeyboardSearch.ts
- hooks/useSearch.ts
- utils/mdxUtils.ts
* Mobile menu now animates in and out
* Search also search description and content
* Max of 10 search items
* All 3D libraries share the same search
* Better order and highlight
> Small improvements

- components/Seo.tsx
- css/main.css
- pages/_app.tsx
> feat: update typography

- components/Search/SearchModal.tsx
- components/mdx/Codesandbox.tsx
- components/mdx/Demo.tsx
- components/mdx/DemoGrid.tsx
- components/mdx/GridUsedBy.tsx
- components/mdx/Storybook.tsx
- components/mdx/YoutubeEmbed.tsx
- components/mdx/index.tsx
- css/main.css
- package.json
- tailwind.config.js
Local dev is so much faster now
> Use Tailwind Jit

- components/Search/index.tsx
Implements quick search text that's responsive, described in https://github.com/pmndrs/website/issues/50#issuecomment-827152527
Closes #50.
This is taken almost straight up from Tailwind's docs website: https://github.com/tailwindlabs/tailwindcss.com/blob/0ce320045d2836ea6fc68ccb834c93364536f731/src/components/Search.js#L67
> feat: responsive quick search text

- components/Layout.tsx
- components/mdx/Sandbox.tsx
- next.config.js
> [Docs] Fix TOC showing 0 when empty, and CLS on showcase

- docs/jotai/api/utils.mdx
close https://github.com/pmndrs/jotai/issues/436
> Add TypeScript subsection for atomFamily

- docs/jotai/integrations/redux.mdx
> fix: Codesandbox link for Jotai/redux

- docs/react-three-fiber/getting-started/introduction.mdx
looks like a find & replace gone awry
> docs: fix postprocessing link

- docs/a11y/roles/content.mdx
small text change and using "they" to be inclusive.
> pronoun to "they" and small grammar change

- docs/jotai/api/utils.mdx
for https://github.com/pmndrs/jotai/pull/407
> [docs/jotai] add utils/atomWithHash

- docs/jotai/api/utils.mdx
Docs for https://github.com/pmndrs/jotai/pull/441
> fix(docs/jotai): freezeAtom utils

- docs/jotai/basics/async.mdx
close https://github.com/pmndrs/jotai/issues/276
> Explain how async atoms trigger Suspense fallback

- docs/jotai/guides/atoms-in-atom.mdx
close https://github.com/pmndrs/jotai/issues/435
> docs(jotai): add guides atoms in atom

- docs/react-three-fiber/API/canvas.mdx
add missing prop & note regarding non-reactive props
> docs(r3f): update canvas api docs

- docs/jotai/api/devtools.mdx
- docs/jotai/guides/testing.mdx
See https://github.com/pmndrs/jotai/issues/252
> docs(Jotai): Add testing chapter

- docs/react-three-fiber/API/objects.mdx
- docs/react-three-fiber/advanced/how-it-works.mdx
Improve wording and add example
> Update r3f docs

- docs/react-three-fiber/getting-started/your-first-scene.mdx
fixed a typo
we see can can optionally to we see it can optionally
> fixed typo in getting started

- docs/jotai/basics/async.mdx
> async.mdx fix typo

- docs/jotai/api/utils.mdx
Relevant to https://github.com/pmndrs/jotai/pull/537 changes
> docs: add doc for atomWithDefault refresh feature

- docs/jotai/api/utils.mdx
Relevant to https://github.com/pmndrs/jotai/pull/552
> Update doc for `atomWithDefault` reset strategy

- docs/react-three-fiber/advanced/pitfalls.mdx
'probablic' is not a real English word, assumed 'problematic' is what was intended. Could be wrong as its present in a few research papers I found on Google, but I as a reader couldn't figure out what it meant.
> Replaced a non-word

- docs/react-three-fiber/getting-started/loading-textures.mdx
change from geometry to material
> Fixed map being applied to wrong component

- docs/react-three-fiber/API/hooks.mdx
Fix typo from "your" to "you" - it's about the small things!
> Fix typo from "your" to "you"

- docs/react-three-fiber/API/additional-exports.mdx
- docs/react-three-fiber/API/events.mdx
- docs/react-three-fiber/API/hooks.mdx
- docs/react-three-fiber/API/objects.mdx
- docs/react-three-fiber/API/render-function.mdx
- docs/react-three-fiber/advanced/gotchas.mdx
- docs/react-three-fiber/advanced/pitfalls.mdx
- docs/react-three-fiber/advanced/scaling-performance.mdx
- docs/react-three-fiber/getting-started/installation.mdx
- docs/react-three-fiber/getting-started/introduction.mdx
- docs/react-three-fiber/getting-started/your-first-scene.mdx
- docs/react-three-fiber/tutorials/basic-animations.mdx
- docs/react-three-fiber/tutorials/how-it-works.mdx
- docs/react-three-fiber/tutorials/loading-models.mdx
- docs/react-three-fiber/tutorials/loading-textures.mdx
- docs/react-three-fiber/tutorials/testing.mdx
Fixes spelling/grammar issues, inconsistent references.
> docs(R3F): cleanup

- docs/react-three-fiber/API/hooks.mdx
This change makes the intention clear / removes ambiguity
> docs(R3F): clarify intentions

- docs/jotai/api/core.mdx
https://github.com/pmndrs/jotai/pull/640
> [docs/jotai] useAtom scope instead of atom scope

- docs/jotai/basics/showcase.mdx
codesandbox link for showcase is broken. because `master` branch is not exists.
so i changed `master` to `main`.
Thank you!
> docs(Jotai): fix broken showcase link

- docs/jotai/integrations/query.mdx
Went through an initial pass at how to improve the query docs a bit -- will be back with more changes!
cc @dai-shi
> chore: update jotai/query docs

- pages/[...slug].tsx
This serializes docs' descriptions to also support markdown, as seen in Jotai:
> fix: serialize docs' frontmatter

- components/footer.js
- next.config.js
- package.json
- pages/_app.js
- pages/_document.js
Streamlines build dependencies and de-dups meta tags. Also disabled workbox in development due to it compiling on each save and slowing builds.
> chore(master): cleanup

- docs/react-three-fiber/advanced/gotchas.mdx
> Fix link in Gotchas section

- docs/jotai/integrations/immer.mdx
> fic(docs/jotai): broken link to sandbox for atomWithImmer

- css/main.css
Fix for the section 'What does it look like?', where line breaks currently allows words to break:
`Let's make a re-usable component that has its ow
n state, reacts to user-input and participates in th
e render-loop. (live demo).`
> Avoid breaking words on line breaks.

- components/footer.js
Better if the footer links open in a new window?
> Footer links update.

- components/mdx/Demo.tsx
- components/mdx/Sandbox.tsx
- pages/api/get-sandbox.ts
Codesandbox types were fragmented and undocumented between components. This will be the first step towards unifying these components.
> chore: cleanup codesandbox types

- components/Layout.tsx
- components/Toc.tsx
- pages/[...slug].tsx
Shows active sections in the sidebar by observing headings as they enter/leave view.
https://user-images.githubusercontent.com/23324155/143797154-c1022821-e76a-4ba3-874c-8efd4f8ffe70.mp4
> feat(ToC): indicate active sections

- docs/react-three-fiber/getting-started/examples.mdx
Just added a tiny `Source by Marcin Ignac:` to the first line of code, just to make sure it's properly attributed.
In general, we should:
- find a good way to attribute the examples
- maybe move the sandboxes to the poimandres org on codesandbox and give everyone write permissions so we don't have to make forks if we have to make changes
cc @drcmda
> Updates one of the examples with proper attribution in the sandbox

- docs/react-three-fiber/tutorials/how-it-works.mdx
- docs/react-three-fiber/tutorials/testing.mdx
- docs/react-three-fiber/tutorials/typescript.mdx
- docs/react-three-fiber/tutorials/using-with-react-spring.mdx
Based on [this tweet](https://twitter.com/sebastienlorber/status/1467195109066354696).
- [Live link](https://website-git-ref-typescript-pmndrs.vercel.app/react-three-fiber/tutorials/typescript)
> docs(R3F): add TypeScript tutorial

- package.json
- src/components/Codesandbox.tsx
- src/components/Icon.tsx
- src/components/Layout.tsx
- src/components/Search/SearchModal.tsx
- src/components/Search/index.tsx
- yarn.lock
Removes slow layout transitions that were a bit disruptive and cleans up mobile nav.
> refactor: cleanup layout

- src/pages/api/get-image.ts
- src/utils/docs.ts
Prefers to not inline local images from markdown.
> fix: don't inline images

- src/pages/main.css
Addresses style issues detailed in https://github.com/pmndrs/zustand/issues/1218.
> fix: tweak code and summary styles

- src/components/Post.tsx
- src/data/libraries.ts
Small PR: Add link to Valtio as suggested in https://github.com/pmndrs/valtio/issues/551.
| Before | After |
|--------|-------|
|  <img width="800" alt="image" src="https://user-images.githubusercontent.com/7823011/191616483-b9ed2520-4c57-4624-8abd-be66ea1f9370.png">      |     <img width="800" alt="image" src="https://user-images.githubusercontent.com/7823011/191616452-64fdbc0e-2cb0-49a9-9a1a-dd37605f6923.png">|
> Add link to Valtio

- src/components/Nav.tsx
Follow-up to https://github.com/pmndrs/website/pull/251#discussion_r964587330. Fixes SSR mismatches from navlinks and Next context. Also silenced invalid table HTML errors with https://github.com/pmndrs/react-three-fiber/commit/e211dbf09461c153d768cad53d439a5fbdcc0b5e.
> fix(Nav): check navlink visibility on client

- package.json
- src/components/Post.tsx
- src/components/Seo.tsx
- src/hooks/useDocs.ts
- src/pages/[...slug].tsx
- src/utils/docs.ts
- src/utils/rehype.ts
- src/utils/text.ts
- yarn.lock
Improves parsing issues that were addressed in #253 and aligns id handling. All CSBs are fetched in lockstep to prepare for #248.
> refactor: improve parsing

- src/components/Search/SearchModal.tsx
This pull request takes care of the problem described in the issue #268.
Fixes #268.
🍀
> Fixing the Issue With Modal Backdrop

- src/components/Layout.tsx
> fix(Layout): restore mobile menu background

- package.json
- src/components/Codesandbox.tsx
- src/components/Search/SearchModalContainer.tsx
- src/components/Search/index.tsx
- src/hooks/useCSB.ts
- src/hooks/useDocs.ts
- src/utils/docs.ts
- src/utils/rehype.ts
**Current behavior**
Search mechanism only look for title and description
**Expected behavior**
Search mechanism look for title, description and content
> Improve docs search

- src/data/libraries.ts
- src/pages/index.tsx
Added a reference to uikit to the libraries.
For now just for building a preview of the docs to share them and receive feedback
> Add reference to uikit docs

- docs/getting-started/authoring.mdx
- src/app/[...slug]/DocsContext.tsx
- src/app/[...slug]/layout.tsx
- src/utils/docs.tsx
https://discord.com/channels/740090768164651008/1264328004172255393/1280157926841122839
> `source:` frontmatter

- docs/getting-started/authoring.mdx
- src/components/mdx/Sandpack/Sandpack.css
- src/components/mdx/Sandpack/Sandpack.tsx
- src/components/mdx/Sandpack/SandpackCodeViewer.tsx
> files decorators
